
#调试模式：当你触发关键词会同时告诉你触发的是哪个
debug: false

关键词指令映射:
#badword理论上可以用所有字符替换，换成你的触发关键词
  badword1:
    拦截玩家消息: true
    执行指令:
      - "ban {player} 10m 使用禁用词语"
#可以写多个指令
      - "kick {player} 使用了违禁词语"
  badword2:
    拦截玩家消息: true
    执行指令:
      - "mute {player} 5m 使用不当语言"

#你以为这个插件只能禁言？那你就错了~~
  QQ群:
    拦截玩家消息: false
    执行指令:
      - "tell {player} 问腐竹"
